CREATE TABLE `user_subscription` (
  `user_subscription_id` int NOT NULL AUTO_INCREMENT,
  `customer_id` int NOT NULL,
  `customer_address_id` int DEFAULT NULL,
  `subscription_package_id` int NOT NULL,
  `package_option_id` int NOT NULL,
  `initial_product_id` INT,
  `initial_addon_id` INT,
  `delivery_slot_id` int NOT NULL,
  `subscription_type_id` int NOT NULL,
  `subscription_start_date` datetime(6) NOT NULL,
  `subscription_end_date` datetime(6) NOT NULL,
  `subscription_actual_end_date` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `subscription_renewal_date` datetime(6) NOT NULL,
  `user_subscription_detail` json DEFAULT NULL,
  `is_active` bit(1) NOT NULL DEFAULT b'1',
  `created_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`user_subscription_id`),
  KEY `FK_user_subscription_cust_id_idx` (`customer_id`),
  KEY `FK_user_subscription_sub_pkg_id_idx` (`subscription_package_id`),
  KEY `FK_user_subscription_pkg_option_id_idx` (`package_option_id`),
  KEY `FK_user_subscription_pkg_detail_id_idx` (`subscription_package_details_id`),
  KEY `FK_user_subscription_init_prod_addon_id_idx` (`initial_product_addon_id`),
  KEY `FK_user_subscription_delivery_slot_id_idx` (`delivery_slot_id`),
  KEY `FK_user_subscription_subscription_type_id_idx` (`subscription_type_id`),
  KEY `FK_user_subscription_cust_address_id_idx` (`customer_address_id`),
  CONSTRAINT `FK_user_subscription_cust_address_id` FOREIGN KEY (`customer_address_id`) REFERENCES `customer_address` (`customer_address_id`),
  CONSTRAINT `FK_user_subscription_cust_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`),
  CONSTRAINT `FK_user_subscription_delivery_slot_id` FOREIGN KEY (`delivery_slot_id`) REFERENCES `delivery_slot` (`delivery_slot_id`),
  CONSTRAINT `FK_user_subscription_init_prod_addon_id` FOREIGN KEY (`initial_product_addon_id`) REFERENCES `product_addon` (`product_addon_id`),
  CONSTRAINT `FK_user_subscription_pkg_detail_id` FOREIGN KEY (`subscription_package_details_id`) REFERENCES `subscription_package_details` (`subscription_package_details_id`),
  CONSTRAINT `FK_user_subscription_pkg_option_id` FOREIGN KEY (`package_option_id`) REFERENCES `package_option` (`package_option_id`),
  CONSTRAINT `FK_user_subscription_sub_pkg_id` FOREIGN KEY (`subscription_package_id`) REFERENCES `subscription_package` (`subscription_package_id`),
  CONSTRAINT `FK_user_subscription_subscription_type_id` FOREIGN KEY (`subscription_type_id`) REFERENCES `subscription_type` (`subscription_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;
